import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

test('operations page renders model strategy pressure from operations api', () => {
  const operationsView = readFileSync(join(process.cwd(), 'src/views/operations.vue'), 'utf8')

  assert.match(operationsView, /loadStrategyPressure/)
  assert.match(operationsView, /get<StrategyPressureItem\[]>\('\/operations\/strategy-pressure'\)/)
  assert.match(operationsView, /strategyPressureItems/)
  assert.match(operationsView, /loadTelemetryReadiness/)
  assert.match(operationsView, /get<TelemetryReadinessItem\[]>\('\/operations\/telemetry-readiness'\)/)
  assert.match(operationsView, /telemetryReadinessItems/)
  assert.match(operationsView, /loadOperationsDashboard/)
  assert.match(operationsView, /get<OperationDashboard>\('\/operations\/dashboard'\)/)
  assert.match(operationsView, /loadOwnerLoad/)
  assert.match(operationsView, /get<OperationOwnerLoad\[]>\('\/operations\/owner-load'\)/)
  assert.match(operationsView, /loadRemediationQueue/)
  assert.match(operationsView, /get<OperationalFinding\[]>\('\/operations\/remediation-queue\?limit=20'\)/)
  assert.match(operationsView, /handleQueueAction/)
  assert.match(operationsView, /post\(endpoint\)/)
  assert.match(operationsView, /\/operations\/remediation-queue\/\$\{record\.findingId\}\/confirm/)
  assert.match(operationsView, /\/operations\/remediation-queue\/\$\{record\.findingId\}\/dismiss/)
  assert.match(operationsView, /确认有效/)
  assert.match(operationsView, /标记误报/)
  assert.match(operationsView, /查看 Review/)
  assert.match(operationsView, /loadRuleLearningCandidates/)
  assert.match(operationsView, /get<RuleLearningCandidate\[]>\('\/operations\/rule-learning-candidates\?limit=20'\)/)
  assert.match(operationsView, /handleRuleLearningAction/)
  assert.match(operationsView, /\/operations\/rule-learning-candidates\/\$\{candidate\.findingId\}\/accept/)
  assert.match(operationsView, /\/operations\/rule-learning-candidates\/\$\{candidate\.findingId\}\/reject/)
  assert.match(operationsView, /已采纳规则学习候选/)
  assert.match(operationsView, /已拒绝规则学习候选/)
  assert.match(operationsView, /loadBusinessImpact/)
  assert.match(operationsView, /get<BusinessImpactEstimate>\('\/operations\/business-impact'\)/)
  assert.match(operationsView, /row-key="findingId"/)
  assert.match(operationsView, /pressureScore/)
  assert.match(operationsView, /confirmationRatePercent/)
  assert.match(operationsView, /falsePositiveProxyPercent/)
  assert.match(operationsView, /strategyHitRatePercent/)
  assert.match(operationsView, /crossHitRatePercent/)
  assert.match(operationsView, /judgeFailureRatePercent/)
})

test('backend exposes operations queue action endpoints', () => {
  const controller = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/controller/OperationsController.java'), 'utf8')
  const service = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/service/impl/OperationsRemediationQueueServiceImpl.java'), 'utf8')
  const repository = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/infrastructure/persistence/MybatisOperationsRemediationQueueRepository.java'), 'utf8')

  assert.match(controller, /@PostMapping\("\/remediation-queue\/\{findingId\}\/confirm"\)/)
  assert.match(controller, /@PostMapping\("\/remediation-queue\/\{findingId\}\/dismiss"\)/)
  assert.match(service, /updateHumanStatus\(findingId, HumanStatus\.CONFIRMED\)/)
  assert.match(service, /updateHumanStatus\(findingId, HumanStatus\.DISMISSED\)/)
  assert.match(repository, /reviewFindingMapper\.updateById\(finding\)/)
})

test('backend persists operations rule learning decisions', () => {
  const controller = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/controller/OperationsController.java'), 'utf8')
  const service = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/service/impl/OperationsRemediationQueueServiceImpl.java'), 'utf8')
  const repository = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/infrastructure/persistence/JdbcOperationsRuleLearningDecisionRepository.java'), 'utf8')
  const migration = readFileSync(join(process.cwd(), '../review-agent-server/src/main/resources/db/migration/V13__operations_rule_learning_decision.sql'), 'utf8')

  assert.match(controller, /@PostMapping\("\/rule-learning-candidates\/\{findingId\}\/accept"\)/)
  assert.match(controller, /@PostMapping\("\/rule-learning-candidates\/\{findingId\}\/reject"\)/)
  assert.match(service, /acceptRuleLearningCandidate/)
  assert.match(service, /rejectRuleLearningCandidate/)
  assert.match(service, /listDecidedFindingIds\(MAX_LIMIT\)/)
  assert.match(repository, /INSERT INTO operations_rule_learning_decision/)
  assert.match(repository, /ON DUPLICATE KEY UPDATE/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS operations_rule_learning_decision/)
  assert.match(migration, /UNIQUE KEY uk_rule_learning_decision_finding/)
})
