import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import test from 'node:test'

test('operations page renders model strategy pressure from operations api', () => {
  const operationsView = readFileSync(join(process.cwd(), 'src/views/operations.vue'), 'utf8')

  assert.match(operationsView, /loadStrategyPressure/)
  assert.match(operationsView, /get<StrategyPressureItem\[]>\('\/operations\/strategy-pressure'\)/)
  assert.match(operationsView, /strategyPressureItems/)
  assert.match(operationsView, /loadTelemetryReadiness/)
  assert.match(operationsView, /get<TelemetryReadinessItem\[]>\('\/operations\/telemetry-readiness'\)/)
  assert.match(operationsView, /telemetryReadinessItems/)
  assert.match(operationsView, /loadCiHealthActions/)
  assert.match(operationsView, /get<OperationsCiHealthAction\[]>\('\/operations\/ci-health-actions'\)/)
  assert.match(operationsView, /ciHealthActions/)
  assert.match(operationsView, /CI Health Actions/)
  assert.match(operationsView, /ciActionSeverityColor/)
  assert.match(operationsView, /retryOperationsCiWriteback/)
  assert.match(operationsView, /post<unknown>\(`\/integration\/ci-config\/writebacks\/\$\{action\.latestWritebackId\}\/retry`\)/)
  assert.match(operationsView, /refreshOperationsJenkinsResults/)
  assert.match(operationsView, /post<number>\('\/integration\/ci-config\/writebacks\/jenkins\/refresh\?limit=20'\)/)
  assert.match(operationsView, /sendCiHealthNotification/)
  assert.match(operationsView, /post<\{ actionStatus: string; errorMessage\?: string \| null \}>/)
  assert.match(operationsView, /\/operations\/ci-health-actions\/\$\{encodeURIComponent\(action\.key\)\}\/notify/)
  assert.match(operationsView, /Send notification/)
  assert.match(operationsView, /Retry writeback/)
  assert.match(operationsView, /Refresh Jenkins/)
  assert.match(operationsView, /loadOperationsTasks/)
  assert.match(operationsView, /get<OperationsTask\[]>\('\/operations\/tasks\?limit=20'\)/)
  assert.match(operationsView, /loadOperationsTaskSlaAlerts/)
  assert.match(operationsView, /get<OperationsTask\[]>\('\/operations\/tasks\/sla-alerts\?limit=8'\)/)
  assert.match(operationsView, /SLA Alerts/)
  assert.match(operationsView, /slaStateColor/)
  assert.match(operationsView, /formatRemainingHours/)
  assert.match(operationsView, /operationsTasks/)
  assert.match(operationsView, /Unified Operations Tasks/)
  assert.match(operationsView, /taskSeverityColor/)
  assert.match(operationsView, /syncOperationsTasks/)
  assert.match(operationsView, /post<OperationsTask\[]>\('\/operations\/tasks\/sync\?limit=20'\)/)
  assert.match(operationsView, /closeOperationsTask/)
  assert.match(operationsView, /updateOperationsTaskStatus/)
  assert.match(operationsView, /editOperationsTaskOwner/)
  assert.match(operationsView, /batchAssignOperationsTasks/)
  assert.match(operationsView, /selectedTaskKeys/)
  assert.match(operationsView, /row-selection/)
  assert.match(operationsView, /patch\('\/operations\/tasks\/batch'/)
  assert.match(operationsView, /syncOperationsTaskGitLabIssue/)
  assert.match(operationsView, /post<OperationsExternalIssue>\(`\/operations\/tasks\/\$\{encodeURIComponent\(task\.taskKey\)\}\/gitlab-issue`\)/)
  assert.match(operationsView, /refreshOperationsTaskGitLabIssue/)
  assert.match(operationsView, /post<OperationsExternalIssue>\(`\/operations\/tasks\/\$\{encodeURIComponent\(task\.taskKey\)\}\/gitlab-issue\/refresh`\)/)
  assert.match(operationsView, /linkOperationsTaskExternalIssue/)
  assert.match(operationsView, /post<OperationsExternalIssue>\(`\/operations\/tasks\/\$\{encodeURIComponent\(task\.taskKey\)\}\/external-issue`/)
  assert.match(operationsView, /Link Issue/)
  assert.match(operationsView, /externalIssueStatusColor/)
  assert.match(operationsView, /externalIssueStateColor/)
  assert.match(operationsView, /formatExternalIssueSyncedAt/)
  assert.match(operationsView, /auto sync/)
  assert.match(operationsView, /externalIssueAssignee/)
  assert.match(operationsView, /externalIssueLabels/)
  assert.match(operationsView, /externalUpdatedAt/)
  assert.match(operationsView, /GitLab issue/)
  assert.match(operationsView, /patch\(`\/operations\/tasks\/\$\{encodeURIComponent\(task\.taskKey\)\}`/)
  assert.match(operationsView, /ACCEPTED_RISK/)
  assert.match(operationsView, /encodeURIComponent\(task\.taskKey\)/)
  assert.match(operationsView, /loadOperationsDashboard/)
  assert.match(operationsView, /get<OperationDashboard>\('\/operations\/dashboard'\)/)
  assert.match(operationsView, /loadOwnerLoad/)
  assert.match(operationsView, /get<OperationOwnerLoad\[]>\('\/operations\/owner-load'\)/)
  assert.match(operationsView, /loadRemediationQueue/)
  assert.match(operationsView, /get<OperationalFinding\[]>\('\/operations\/remediation-queue\?limit=20'\)/)
  assert.match(operationsView, /handleQueueAction/)
  assert.match(operationsView, /post\(endpoint\)/)
  assert.match(operationsView, /\/operations\/remediation-queue\/\$\{record\.findingId\}\/confirm/)
  assert.match(operationsView, /\/operations\/remediation-queue\/\$\{record\.findingId\}\/dismiss/)
  assert.match(operationsView, /确认有效/)
  assert.match(operationsView, /标记误报/)
  assert.match(operationsView, /查看 Review/)
  assert.match(operationsView, /loadRuleLearningCandidates/)
  assert.match(operationsView, /get<RuleLearningCandidate\[]>\('\/operations\/rule-learning-candidates\?limit=20'\)/)
  assert.match(operationsView, /handleRuleLearningAction/)
  assert.match(operationsView, /\/operations\/rule-learning-candidates\/\$\{candidate\.findingId\}\/accept/)
  assert.match(operationsView, /\/operations\/rule-learning-candidates\/\$\{candidate\.findingId\}\/reject/)
  assert.match(operationsView, /已采纳规则学习候选/)
  assert.match(operationsView, /已拒绝规则学习候选/)
  assert.match(operationsView, /loadBusinessImpact/)
  assert.match(operationsView, /get<BusinessImpactEstimate>\('\/operations\/business-impact'\)/)
  assert.match(operationsView, /row-key="findingId"/)
  assert.match(operationsView, /pressureScore/)
  assert.match(operationsView, /confirmationRatePercent/)
  assert.match(operationsView, /falsePositiveProxyPercent/)
  assert.match(operationsView, /strategyHitRatePercent/)
  assert.match(operationsView, /crossHitRatePercent/)
  assert.match(operationsView, /judgeFailureRatePercent/)
})

test('backend exposes operations ci health action endpoint', () => {
  const controller = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/controller/OperationsController.java'), 'utf8')
  const service = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/service/impl/OperationsCiHealthActionServiceImpl.java'), 'utf8')
  const vo = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/domain/dto/OperationsCiHealthActionVO.java'), 'utf8')

  assert.match(controller, /@GetMapping\("\/ci-health-actions"\)/)
  assert.match(controller, /ciHealthActions/)
  assert.match(service, /ciStatusWritebackLogService\.listHealth\(HEALTH_SAMPLE_LIMIT\)/)
  assert.match(service, /setOwnerRole/)
  assert.match(service, /setSlaHours/)
  assert.match(service, /setLatestWritebackId/)
  assert.match(service, /setLatestExternalBuildUrl/)
  assert.match(service, /notifyAction/)
  assert.match(service, /CI_HEALTH_NOTIFICATION/)
  assert.match(controller, /@PostMapping\("\/ci-health-actions\/\{actionKey\}\/notify"\)/)
  assert.match(vo, /ownerRole/)
  assert.match(vo, /slaHours/)
  assert.match(vo, /latestWritebackId/)
  assert.match(vo, /latestExternalBuildUrl/)
  assert.match(vo, /recommendation/)
  assert.match(vo, /notificationTitle/)
  assert.match(vo, /notificationDedupKey/)
})

test('backend exposes unified operations task endpoint', () => {
  const controller = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/controller/OperationsController.java'), 'utf8')
  const service = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/service/impl/OperationsTaskServiceImpl.java'), 'utf8')
  const repository = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/infrastructure/persistence/JdbcOperationsTaskRepository.java'), 'utf8')
  const externalIssueRepository = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/infrastructure/persistence/JdbcOperationsExternalIssueRepository.java'), 'utf8')
  const vo = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/domain/dto/OperationsTaskVO.java'), 'utf8')
  const migration = readFileSync(join(process.cwd(), '../review-agent-server/src/main/resources/db/migration/V19__operations_task.sql'), 'utf8')
  const issueMigration = readFileSync(join(process.cwd(), '../review-agent-server/src/main/resources/db/migration/V20__operations_external_issue_link.sql'), 'utf8')
  const scheduler = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/service/OperationsGitLabIssueRefreshScheduler.java'), 'utf8')
  const applicationConfig = readFileSync(join(process.cwd(), '../review-agent-server/src/main/resources/application.yml'), 'utf8')

  assert.match(controller, /@GetMapping\("\/tasks"\)/)
  assert.match(controller, /taskService\.listTasks\(limit\)/)
  assert.match(controller, /@GetMapping\("\/tasks\/sla-alerts"\)/)
  assert.match(controller, /taskService\.listSlaAlerts\(limit\)/)
  assert.match(controller, /@PostMapping\("\/tasks\/sync"\)/)
  assert.match(controller, /@PatchMapping\("\/tasks\/batch"\)/)
  assert.match(controller, /taskService\.updateTasks/)
  assert.match(controller, /@PatchMapping\("\/tasks\/\{taskKey\}"\)/)
  assert.match(controller, /@PostMapping\("\/tasks\/\{taskKey\}\/gitlab-issue"\)/)
  assert.match(controller, /taskService\.syncGitLabIssue\(taskKey\)/)
  assert.match(controller, /@PostMapping\("\/tasks\/\{taskKey\}\/gitlab-issue\/refresh"\)/)
  assert.match(controller, /taskService\.refreshGitLabIssue\(taskKey\)/)
  assert.match(controller, /@PostMapping\("\/tasks\/\{taskKey\}\/external-issue"\)/)
  assert.match(controller, /taskService\.linkExternalIssue\(taskKey, request\)/)
  assert.match(controller, /@PostMapping\("\/tasks\/\{taskKey\}\/close"\)/)
  assert.match(service, /remediationQueueService\.listQueue\(safeLimit\)/)
  assert.match(service, /ciHealthActionService\.listActions\(\)/)
  assert.match(service, /operationsTaskRepository\.upsertTasks\(tasks\)/)
  assert.match(service, /ALLOWED_TASK_STATUSES/)
  assert.match(service, /listSlaAlerts/)
  assert.match(service, /enrichSlaState/)
  assert.match(service, /OVERDUE/)
  assert.match(service, /DUE_SOON/)
  assert.match(service, /operationsTaskRepository\.updateTask/)
  assert.match(service, /operationsTaskRepository\.updateTasks/)
  assert.match(service, /normalizeTaskKeys/)
  assert.match(service, /syncGitLabIssue/)
  assert.match(service, /gitLabApiClient\.createIssue/)
  assert.match(service, /refreshGitLabIssue/)
  assert.match(service, /refreshRecentGitLabIssues/)
  assert.match(service, /linkExternalIssue/)
  assert.match(service, /ALLOWED_EXTERNAL_ISSUE_PROVIDERS/)
  assert.match(service, /"JIRA"/)
  assert.match(service, /"ZENTAO"/)
  assert.match(service, /gitLabApiClient\.getIssue/)
  assert.match(service, /operationsTaskRepository\.closeTask\(/)
  assert.match(service, /operationsTaskRepository\.closeTask/)
  assert.match(externalIssueRepository, /operations_external_issue_link/)
  assert.match(externalIssueRepository, /external_issue_state/)
  assert.match(externalIssueRepository, /external_issue_assignee/)
  assert.match(externalIssueRepository, /external_updated_at/)
  assert.match(externalIssueRepository, /recordDetailed/)
  assert.match(externalIssueRepository, /findRecentGitLabRefreshCandidates/)
  assert.match(externalIssueRepository, /external_issue_state <> 'closed'/)
  assert.match(externalIssueRepository, /project_gitlab_config/)
  assert.match(scheduler, /@Scheduled\(fixedDelayString = "\$\{review-agent\.operations\.gitlab-issue-refresh-delay-ms:300000\}"\)/)
  assert.match(scheduler, /taskService\.refreshRecentGitLabIssues\(refreshLimit\)/)
  assert.match(applicationConfig, /gitlab-issue-refresh-delay-ms/)
  assert.match(applicationConfig, /gitlab-issue-refresh-limit/)
  assert.match(issueMigration, /CREATE TABLE IF NOT EXISTS operations_external_issue_link/)
  assert.match(issueMigration, /external_issue_state/)
  assert.match(issueMigration, /external_issue_title/)
  assert.match(issueMigration, /external_issue_labels/)
  assert.match(issueMigration, /external_issue_assignee/)
  assert.match(issueMigration, /external_updated_at/)
  assert.match(repository, /INSERT INTO operations_task/)
  assert.match(repository, /ON DUPLICATE KEY UPDATE/)
  assert.match(repository, /UPDATE operations_task/)
  assert.match(repository, /SET task_status = COALESCE/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS operations_task/)
  assert.match(migration, /UNIQUE KEY uk_operations_task_key/)
  assert.match(service, /setSourceType\("FINDING"\)/)
  assert.match(service, /setSourceType\("CI_HEALTH"\)/)
  assert.match(vo, /taskKey/)
  assert.match(vo, /sourceType/)
  assert.match(vo, /ownerRole/)
  assert.match(vo, /slaHours/)
  assert.match(vo, /closeReason/)
  assert.match(vo, /externalIssue/)
  assert.match(vo, /createdAt/)
  assert.match(vo, /closedAt/)
  assert.match(vo, /slaDueAt/)
  assert.match(vo, /slaState/)
  assert.match(vo, /remainingHours/)
})

test('backend exposes operations queue action endpoints', () => {
  const controller = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/controller/OperationsController.java'), 'utf8')
  const service = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/service/impl/OperationsRemediationQueueServiceImpl.java'), 'utf8')
  const repository = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/infrastructure/persistence/MybatisOperationsRemediationQueueRepository.java'), 'utf8')

  assert.match(controller, /@PostMapping\("\/remediation-queue\/\{findingId\}\/confirm"\)/)
  assert.match(controller, /@PostMapping\("\/remediation-queue\/\{findingId\}\/dismiss"\)/)
  assert.match(service, /updateHumanStatus\(findingId, HumanStatus\.CONFIRMED\)/)
  assert.match(service, /updateHumanStatus\(findingId, HumanStatus\.DISMISSED\)/)
  assert.match(repository, /reviewFindingMapper\.updateById\(finding\)/)
})

test('backend persists operations rule learning decisions', () => {
  const controller = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/controller/OperationsController.java'), 'utf8')
  const service = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/service/impl/OperationsRemediationQueueServiceImpl.java'), 'utf8')
  const repository = readFileSync(join(process.cwd(), '../review-agent-server/src/main/java/com/review/agent/infrastructure/persistence/JdbcOperationsRuleLearningDecisionRepository.java'), 'utf8')
  const migration = readFileSync(join(process.cwd(), '../review-agent-server/src/main/resources/db/migration/V13__operations_rule_learning_decision.sql'), 'utf8')

  assert.match(controller, /@PostMapping\("\/rule-learning-candidates\/\{findingId\}\/accept"\)/)
  assert.match(controller, /@PostMapping\("\/rule-learning-candidates\/\{findingId\}\/reject"\)/)
  assert.match(service, /acceptRuleLearningCandidate/)
  assert.match(service, /rejectRuleLearningCandidate/)
  assert.match(service, /listDecidedFindingIds\(MAX_LIMIT\)/)
  assert.match(repository, /INSERT INTO operations_rule_learning_decision/)
  assert.match(repository, /ON DUPLICATE KEY UPDATE/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS operations_rule_learning_decision/)
  assert.match(migration, /UNIQUE KEY uk_rule_learning_decision_finding/)
})
