CREATE TABLE IF NOT EXISTS operations_external_issue_link (
    id                   BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'Primary key',
    task_key             VARCHAR(160)  NOT NULL COMMENT 'Operations task key',
    provider             VARCHAR(40)   NOT NULL COMMENT 'External issue provider, for example GITLAB',
    issue_status         VARCHAR(40)   NOT NULL COMMENT 'SYNCED/SKIPPED/FAILED',
    external_issue_id    VARCHAR(100)  DEFAULT NULL COMMENT 'Provider issue id',
    external_issue_iid   VARCHAR(100)  DEFAULT NULL COMMENT 'Provider project-scoped issue iid',
    external_issue_url   VARCHAR(500)  DEFAULT NULL COMMENT 'Provider issue web url',
    external_issue_state VARCHAR(40)   DEFAULT NULL COMMENT 'Provider issue state, for example opened/closed',
    external_issue_title VARCHAR(500)  DEFAULT NULL COMMENT 'Provider issue title',
    external_issue_labels VARCHAR(500) DEFAULT NULL COMMENT 'Provider issue labels',
    external_issue_assignee VARCHAR(160) DEFAULT NULL COMMENT 'Provider issue assignee username',
    external_issue_author VARCHAR(160) DEFAULT NULL COMMENT 'Provider issue author username',
    external_updated_at  DATETIME      DEFAULT NULL COMMENT 'Provider issue updated timestamp',
    external_closed_at   DATETIME      DEFAULT NULL COMMENT 'Provider issue closed timestamp',
    request_url          VARCHAR(500)  DEFAULT NULL COMMENT 'Provider API request url',
    error_message        VARCHAR(1000) DEFAULT NULL COMMENT 'Sync error or skip reason',
    synced_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Sync timestamp',
    created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created timestamp',
    updated_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated timestamp',
    INDEX idx_operations_external_issue_task (task_key),
    INDEX idx_operations_external_issue_provider (provider),
    INDEX idx_operations_external_issue_status (issue_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Operations external issue sync link';
